quarkus:
  http:
    test-port: 8091
# configure your datasource
  datasource:
    db-kind: postgresql
    username: ${DB_USER}
    password: ${DB_PASS}
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}

# drop and create the database at startup (use `update` to only update the schema)
  hibernate-orm:
    database:
      generation: none

# configure your flyway settings
  flyway:
    migrate-at-start: true
    clean-at-start: false

# configure your jacoco settings
  jacoco:
    report-location: target/site
